### ISSUE TITLE
Question not an issue

### ISSUE THREAD

**Issue by 12nick12** [bahamas10/zfs-snapshot-all#1]
Is there any way to name the snapshot by date like YYYMMDD_HHMM? Thanks.

**Comment by bahamas10** [comment]
So, short answer, yes.

Long answer... this gets a little tricky and may require me to rethink the design of this program (namely, how arguments are taken).

Basically, putting in the epoch time is a nice thing that this script does, but it relies on `date`, and not all systems ship with the same version... I have an idea to allow the caller (the user of this program) to specify an exact name to use, where they could pass in their own date... i'll have a branch in a sec for you to look at that *may* do what you want.

**Comment by bahamas10** [comment]
take a look at the code in https://github.com/bahamas10/zfs-snapshot-all/pull/2

**Comment by 12nick12** [comment]
Dude you are amazing. Hopefully one day I'll have the understanding of bash you have.

**Comment by bahamas10** [comment]
Thank you! :)

Everything I know I have learned from this site https://mywiki.wooledge.org/BashGuide/Practices and the #bash IRC channel on freenode.

If you are interested in my personal styleguide check out https://www.daveeddy.com/bash
